-- BRANDS 테이블 생성
CREATE TABLE BRANDS(
    BRAND_ID NUMBER PRIMARY KEY,
    BRAND_NAME VARCHAR2(100) NOT NULL
);
CREATE TABLE PRODUCTS(
    PRODUCT_NO NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    PRODUCT_PRICE NUMBER NOT NULL,
    BRAND_CODE NUMBER REFERENCES BRANDS,
    SERIAL_NO VARCHAR2(100),
    SOLD_OUT CHAR(1) DEFAULT 'N' CHECK(SOLD_OUT IN ('Y', 'N'))
);

ALTER TABLE PRODUCTS
MODIFY PRODUCT_NAME VARCHAR2(20);
-- PRODUCT_NAME 표에 VARCHAR2 길이가 20 바이트라고 적혀있으므로 수정

ALTER TABLE PRODUCTS
MODIFY SERIAL_NO UNIQUE;
-- UNIQUE 추가

-- SEQ_BRAND_ID 시퀀스 생성
CREATE SEQUENCE SEQ_BRAND_ID
START WITH 100
INCREMENT BY 100
MAXVALUE 500
NOCYCLE;

ALTER SEQUENCE SEQ_BRAND_ID
MAXVALUE 1000;
-- MAXVALUE 수정

-- SEQ_PRODUCT_NO 시퀀스 생성
CREATE SEQUENCE SEQ_PRODUCT_NO
START WITH 1
INCREMENT BY 1
MAXVALUE 10000
NOCYCLE;

INSERT INTO BRANDS VALUES (SEQ_BRAND_ID.NEXTVAL, '삼성');
INSERT INTO BRANDS VALUES (SEQ_BRAND_ID.NEXTVAL, '애플');
-- BRAND_ID는 PRIMARY KEY로 인해 같은 번호로 등록할 수 없으므로, 애플에 다음번호를 매겨야해서 CURRVAL말고 NEXTVAL을 써야한다.

INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S8', 800000, 100, 'S8','Y');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S9', 900000, 100, 'S9','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S10', 1000000, 100, 'S10','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '아이폰9S', 900000, 200, '9S','N');
INSERT INTO PRODUCTS VALUES (SEQ_PRODUCT_NO.NEXTVAL, '아이폰10S', 1000000, 200, '10S','N');

SELECT P.PRODUCT_NAME, P.PRODUCT_PRICE, B.BRAND_NAME ,P.SOLD_OUT
FROM PRODUCTS P
JOIN BRANDS B ON (P.BRAND_CODE = B.BRAND_ID);
--브랜드 네임 추가

DROP SEQUENCE SEQ_BRAND_ID;
DROP SEQUENCE SEQ_PRODUCT_NO;
DROP TABLE PRODUCTS;
DROP TABLE BRANDS;

--컬럼 추가
COMMENT ON COLUMN BRANDS.BRAND_ID IS '브랜드번호';
COMMENT ON COLUMN BRANDS.BRAND_NAME IS '브랜드명';
COMMENT ON COLUMN PRODUCTS.PRODUCT_NO IS '상품번호';
COMMENT ON COLUMN PRODUCTS.PRODUCT_NAME IS '상품명';
COMMENT ON COLUMN PRODUCTS.PRODUCT_PRICE IS '상품가격';
COMMENT ON COLUMN PRODUCTS.BRAND_CODE IS '브랜드번호';
COMMENT ON COLUMN PRODUCTS.SERIAL_NO IS '고유번호';
COMMENT ON COLUMN PRODUCTS.SOLD_OUT IS '품절여부';