CREATE TABLE MEMBER_GRADE(
    GRADE_CODE NUMBER PRIMARY KEY,
    GRADE_NAME VARCHAR2(20) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE
);

INSERT INTO MEMBER_GRADE VALUES (10, '일반회원' ,'2023/11/14');
INSERT INTO MEMBER_GRADE VALUES (20, '우수회원' ,'2023/11/15');
INSERT INTO MEMBER_GRADE VALUES (30, '특별회원', DEFAULT);

SELECT * FROM MEMBER_GRADE;

commit;

SELECT * FROM MEMBER_GRADE;
SELECT * FROM MEMBER_GRADE
WHERE GRADE_CODE = 30;

CREATE SEQUENCE SEQ_GCODE
START WITH 40
INCREMENT BY 10;

SELECT SEQ_GCODE.NEXTVAL FROM DUAL;

INSERT INTO MEMBER_GRADE VALUES(SEQ_GCODE.NEXTVAL, 'VVIP', DEFAULT);

UPDATE MEMBER_GRADE
SET GRADE_NAME = '덜착한회원',
    CREATE_DATE = '2023/11/14'
WHERE GRADE_CODE = 100;

DELETE
FROM MEMBER_GRADE
WHERE GRADE_CODE = 100;